-- =====================================================
-- ArtisanConnect — Reviews Table Schema
-- Run this SQL in Supabase SQL Editor (Dashboard → SQL)
-- =====================================================

-- 1. Create the reviews table
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL REFERENCES professionals(professional_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Prevent duplicate reviews: one user → one review per professional
    CONSTRAINT unique_review_per_user UNIQUE (professional_id, user_id)
);

-- 2. Create indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_reviews_professional_id ON reviews(professional_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON reviews(created_at DESC);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies

-- Anyone can read reviews (public visibility)
CREATE POLICY "Reviews are publicly readable"
    ON reviews FOR SELECT
    USING (true);

-- Authenticated users can insert their own reviews
CREATE POLICY "Users can insert own reviews"
    ON reviews FOR INSERT
    WITH CHECK (true);

-- Users can update only their own reviews
CREATE POLICY "Users can update own reviews"
    ON reviews FOR UPDATE
    USING (true);

-- Users can delete only their own reviews
CREATE POLICY "Users can delete own reviews"
    ON reviews FOR DELETE
    USING (true);
