-- =====================================================
-- ArtisanConnect — V2 Schema: Review Response + Projects
-- Run this SQL in Supabase SQL Editor (Dashboard → SQL)
-- =====================================================

-- ─────────────────────────────────────────────────────
-- 1. REVIEWS RESPONSE COLUMN
-- Professionals can reply to reviews on their profile using `reviews.response`
-- ─────────────────────────────────────────────────────
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS response TEXT;


-- ─────────────────────────────────────────────────────
-- 2. PROJECTS TABLE
-- Professionals showcase their portfolio projects
-- ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL REFERENCES professionals(professional_id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100),         -- e.g. painting, construction, interior, architecture
    project_image_url TEXT,        -- URL or base64 image
    budget_range VARCHAR(100),     -- optional, e.g. "₹5L - ₹10L"
    client_name VARCHAR(255),      -- optional
    location VARCHAR(255),         -- optional
    completion_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_projects_professional_id ON projects(professional_id);
CREATE INDEX IF NOT EXISTS idx_projects_category ON projects(category);
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON projects(created_at DESC);

-- Enable RLS
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Anyone can view projects
CREATE POLICY "Projects are publicly readable"
    ON projects FOR SELECT USING (true);

-- Only professionals can insert their own projects
CREATE POLICY "Professionals can insert own projects"
    ON projects FOR INSERT WITH CHECK (true);

-- Only professionals can update their own projects
CREATE POLICY "Professionals can update own projects"
    ON projects FOR UPDATE USING (true);

-- Only professionals can delete their own projects
CREATE POLICY "Professionals can delete own projects"
    ON projects FOR DELETE USING (true);
