-- =====================================================
-- ArtisanConnect — V2 Schema: Review Replies + Projects
-- Run this SQL in Supabase SQL Editor (Dashboard → SQL)
-- =====================================================

-- ─────────────────────────────────────────────────────
-- 1. REVIEW REPLIES TABLE
-- Professionals can reply to reviews on their profile
-- ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS review_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    professional_id BIGINT NOT NULL REFERENCES professionals(professional_id) ON DELETE CASCADE,
    reply_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Only one reply per review (professional replies once)
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_reply_per_review ON review_replies(review_id);
CREATE INDEX IF NOT EXISTS idx_replies_professional_id ON review_replies(professional_id);

-- Enable RLS
ALTER TABLE review_replies ENABLE ROW LEVEL SECURITY;

-- Anyone can read replies
CREATE POLICY "Replies are publicly readable"
    ON review_replies FOR SELECT USING (true);

-- Only professionals can insert replies
CREATE POLICY "Professionals can insert replies"
    ON review_replies FOR INSERT WITH CHECK (true);

-- Professionals can update their own replies
CREATE POLICY "Professionals can update own replies"
    ON review_replies FOR UPDATE USING (true);

-- Professionals can delete their own replies
CREATE POLICY "Professionals can delete own replies"
    ON review_replies FOR DELETE USING (true);


-- ─────────────────────────────────────────────────────
-- 2. PROJECTS TABLE
-- Professionals showcase their portfolio projects
-- ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL REFERENCES professionals(professional_id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100),         -- e.g. painting, construction, interior, architecture
    project_image_url TEXT,        -- URL or base64 image
    budget_range VARCHAR(100),     -- optional, e.g. "₹5L - ₹10L"
    client_name VARCHAR(255),      -- optional
    location VARCHAR(255),         -- optional
    completion_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_projects_professional_id ON projects(professional_id);
CREATE INDEX IF NOT EXISTS idx_projects_category ON projects(category);
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON projects(created_at DESC);

-- Enable RLS
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Anyone can view projects
CREATE POLICY "Projects are publicly readable"
    ON projects FOR SELECT USING (true);

-- Only professionals can insert their own projects
CREATE POLICY "Professionals can insert own projects"
    ON projects FOR INSERT WITH CHECK (true);

-- Only professionals can update their own projects
CREATE POLICY "Professionals can update own projects"
    ON projects FOR UPDATE USING (true);

-- Only professionals can delete their own projects
CREATE POLICY "Professionals can delete own projects"
    ON projects FOR DELETE USING (true);
