-- =====================================================
-- ArtisanConnect — Schema: Cities Management
-- Run this SQL in Supabase SQL Editor (Dashboard → SQL)
-- =====================================================

CREATE TABLE IF NOT EXISTS cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster active city lookups
CREATE INDEX IF NOT EXISTS idx_cities_is_active ON cities(is_active);

-- Enable RLS
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;

-- Anyone can read active cities (for frontend)
CREATE POLICY "Cities are publicly readable"
    ON cities FOR SELECT USING (true);

-- Only admins can insert cities
CREATE POLICY "Admins can insert cities"
    ON cities FOR INSERT WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- Only admins can update cities
CREATE POLICY "Admins can update cities"
    ON cities FOR UPDATE USING (auth.jwt() ->> 'role' = 'admin');

-- Only admins can delete cities
CREATE POLICY "Admins can delete cities"
    ON cities FOR DELETE USING (auth.jwt() ->> 'role' = 'admin');

-- Insert some default Indian cities (if they don't exist)
INSERT INTO cities (name, is_active)
VALUES 
    ('Hyderabad', true),
    ('Karimnagar', true),
    ('Warangal', true),
    ('Sircilla', true),
    ('Mumbai', false),
    ('Delhi', false)
ON CONFLICT (name) DO NOTHING;
